clear all;
close all;

% Load DEPAF source code:
addpath(genpath('..\..\DEPAF_src_replication'));

% Data path and POI path:
dataPath = '..\datasets\sequence-as-stack-MT0.N2.HD-DH-Exp.tif'; % Image data path
POIPath = '..\datasets\calibrated_double_helix_PSFs_3D_SMLM_benchmarking.mat'; % POI image data path
lambda = 0.021; % Regularization intensity coefficient

% Data loading parameters:
trainIdxRange = 1:2500; % Training set patch sampling range index
valIdxRange = 1:2500; % Validation set patch sampling range index

% Model saving parameters:
modelSavePath = '..\models\'; % Path to save the model

% Preprocessing parameters:
upsamplRatio = [1.5 1.5 1]; % Upsampling ratio
interpMethod = 'spline'; % Interpolation method, options: 'spline', 'linear', 'nearest', 'cubic'

% Model structure parameters:
encoderDepth = 2; % Depth of U-net encoder part (total depth is approximately twice this)

% U-net model training parameters:
patchSize = [96 96]; % Patch size for sampling
trainPatchNum = 2500; % Number of patches for training set
valPatchNum = 64; % Number of patches for validation set
learningRate = 1e-3; % Learning rate
minLR = 1e-4; % Lower limit for learning rate decay
miniBatchSize = 8; % Batch size per iteration
maxEpochs = 1000; % Maximum training epochs
valFreq = 20; % Validation frequency (validate every valFreq batches)
maxPatience = 50; % Early stopping patience (stops training if validation loss does not decrease for this many validations)
learnBG = true; % Whether to learn the background
verbose = true; % Whether to display processing images
useGPU = true; % Whether to use GPU

% Bayesian estimation best threshold search parameters:
useParallel = true; % Whether to use parallel computation
parNum = 3; % Number of parallel pool workers
patchNumForThreshSearch = 512; % Number of samples for best threshold search

DEPAFTrain(dataPath, POIPath, lambda, ...
    'trainIdxRange', trainIdxRange, ...
    'valIdxRange', valIdxRange, ...
    'upsamplRatio', upsamplRatio, ...
    'interpMethod', interpMethod, ...
    'patchSize', patchSize, ...
    'trainPatchNum', trainPatchNum, ...
    'valPatchNum', valPatchNum, ...
    'encoderDepth', encoderDepth, ...
    'learningRate', learningRate, ...
    'minLR', minLR, ...
    'miniBatchSize', miniBatchSize, ...
    'maxEpochs', maxEpochs, ...
    'valFreq', valFreq, ...
    'maxPatience', maxPatience, ...
    'learnBG', learnBG, ...
    'verbose', verbose, ...
    'useGPU', useGPU, ...
    'useParallel', useParallel, ...
    'parNum', parNum, ...
    'patchNumForThreshSearch', patchNumForThreshSearch, ...
    'modelSavePath', modelSavePath);